import {FormEvent,useEffect,useMemo,useState} from'react'
import type{Assignment,AuthState as Auth,Rubric,Submission,View}from'./types'
import{login}from'./api/auth'
import{apiRequest as req}from'./api/client'
import{clearAuth,loadAuth,saveAuth}from'./auth/storage'
import{useCourseData}from'./hooks/useCourseData'
import{Empty,Head,Score,Title}from'./components/ui'
const ico:Record<string,string>={home:'⌂',assignments:'▤',submissions:'⇩',publish:'＋',out:'↗',search:'⌕',code:'</>'};
const fmt=(x:string)=>new Date(x).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}),left=(x:string)=>Math.ceil((new Date(x).getTime()-Date.now())/86400000);
function App(){const[a,setA]=useState<Auth|null>(loadAuth);return a?<Workspace auth={a} logout={()=>{clearAuth();setA(null)}}/>:<Login done={v=>{saveAuth(v);setA(v)}}/>}
function Login({done}:{done:(a:Auth)=>void}){const[u,setU]=useState('teacher'),[p,setP]=useState('CodeEval123!'),[err,setErr]=useState(''),[busy,setBusy]=useState(false);async function go(e:FormEvent){e.preventDefault();setBusy(true);try{done(await login(u,p))}catch(e){setErr(e instanceof Error?e.message:'登录失败')}finally{setBusy(false)}}return <main className="login"><section><Logo/><div><small>AI-POWERED ASSESSMENT</small><h1>让每一行代码<br/>都有回应。</h1><p>从提交到反馈，只需片刻。清晰的评分证据，真正可执行的改进建议。</p></div><b>{'{ code → feedback }'}</b></section><form onSubmit={go}><div><h2>欢迎回来</h2><p>登录你的教学工作台</p></div><label>账号<input value={u} onChange={e=>setU(e.target.value)}/></label><label>密码<input type="password" value={p} onChange={e=>setP(e.target.value)}/></label>{err&&<i className="error">{err}</i>}<button className="primary" disabled={busy}>{busy?'登录中…':'登录'}</button><aside><strong>体验账号</strong><button type="button" onClick={()=>setU('teacher')}>教师 teacher</button><button type="button" onClick={()=>setU('student')}>学生 student</button><small>密码均为 CodeEval123!</small></aside></form></main>}
function Logo(){return <div className="logo"><i>C</i><span>CodeEval</span></div>}
function Workspace({auth,logout}:{auth:Auth;logout:()=>void}){const teacher=auth.user.role==='teacher',[view,setView]=useState<View>('home'),[as,setAs]=useState<Assignment[]>([]),[ss,setSs]=useState<Submission[]>([]),[err,setErr]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Submission>();const load=()=>{setLoading(true);return Promise.all([req('/assignments',auth.token),req('/submissions',auth.token)]).then(([a,s])=>{setAs(a);setSs(s);setErr('')}).catch(e=>setErr(e.message)).finally(()=>setLoading(false))};useEffect(()=>{load()},[]);const avg=ss.length?Math.round(ss.reduce((n,s)=>n+(s.evaluation?.total||0),0)/ss.length):0;return <div className="shell"><aside className="side"><Logo/><nav>{([['home','工作台'],['assignments',teacher?'作业管理':'我的作业'],['submissions',teacher?'提交列表':'提交记录'],...(teacher?[['publish','发布作业']]:[])]as [View,string][]).map(([v,n])=><button className={view===v?'on':''} onClick={()=>{setView(v);setSelected(undefined)}} key={v}><b>{ico[v]}</b>{n}{v==='submissions'&&<em>{ss.length}</em>}</button>)}</nav><footer><i>{auth.user.displayName[0]}</i><span><b>{auth.user.displayName}</b><small>{teacher?'教师账号':'学生账号'}</small></span><button onClick={logout}>{ico.out}</button></footer></aside><main className="work"><header><span><small>数据结构与算法 · 2026 秋季</small><h1>{{home:'工作台',assignments:'作业',submissions:'提交记录',publish:'发布作业'}[view]}</h1></span><b>{teacher?'教师端':'学生端'}</b></header>{err&&<p className="alert">{err}</p>}{loading?<Empty text="正在加载课程数据…"/>:selected?<Detail sub={selected} assignment={as.find(a=>a.id===selected.assignmentId)} back={()=>setSelected(undefined)}/>:view==='home'?<Home teacher={teacher} as={as} ss={ss} avg={avg} go={setView} pick={setSelected}/>:view==='assignments'?(teacher?<TeacherAssignments as={as} ss={ss} go={setView}/>:<StudentAssignments as={as} ss={ss} go={setView}/>):view==='submissions'?<Submissions teacher={teacher} as={as} ss={ss} pick={setSelected}/>:<Publish token={auth.token} done={async()=>{await load();setView('assignments')}}/>}</main></div>}
function Home({teacher,as,ss,avg,go,pick}:{teacher:boolean;as:Assignment[];ss:Submission[];avg:number;go:(v:View)=>void;pick:(s:Submission)=>void}){return <><section className="hero"><div><small>{teacher?'COURSE OVERVIEW':'GOOD MORNING'}</small><h2>{teacher?'今天也一起把反馈做得更好。':'继续保持，你的每次提交都有进步。'}</h2><p>{teacher?'查看最新提交，及时发现共性问题。':'从待完成的作业开始，提交代码即可获得即时评估。'}</p></div><button onClick={()=>go(teacher?'publish':'assignments')}>{teacher?'＋ 发布新作业':'▤ 查看待办作业'}</button></section><section className="stats"><Stat name={teacher?'已发布作业':'全部作业'} n={as.length} note={`${as.filter(a=>left(a.dueAt)>=0).length} 项进行中`}/><Stat name={teacher?'学生提交':'我的提交'} n={ss.length} note="本课程累计"/><Stat name="平均得分" n={ss.length?avg:'—'} note="满分 100"/></section><div className="cols"><section className="panel"><Head name={teacher?'最近提交':'最近反馈'} action={()=>go('submissions')}/>{ss.slice(0,4).map(s=><button className="recent" onClick={()=>pick(s)} key={s.id}><i>{ico.code}</i><span><b>{teacher?s.studentName:as.find(a=>a.id===s.assignmentId)?.title}</b><small>{fmt(s.submittedAt)}</small></span><Score n={s.evaluation?.total}/><em>›</em></button>)}{!ss.length&&<Empty text="还没有提交记录"/>}</section><section className="panel"><Head name={teacher?'作业进度':'即将截止'} action={()=>go('assignments')}/>{as.slice(0,4).map(a=><div className="due" key={a.id}><i><b>{new Date(a.dueAt).getDate()}</b><small>{new Date(a.dueAt).getMonth()+1}月</small></i><span><b>{a.title}</b><small>{a.language} · {teacher?`${ss.filter(s=>s.assignmentId===a.id).length} 份提交`:left(a.dueAt)<0?'已截止':`${left(a.dueAt)} 天后截止`}</small></span></div>)}</section></div></>}
function Stat({name,n,note}:{name:string;n:number|string;note:string}){return <div><small>{name}</small><b>{n}</b><span>{note}</span></div>}
function TeacherAssignments({as,ss,go}:{as:Assignment[];ss:Submission[];go:(v:View)=>void}){const[statuses,setStatuses]=useState<Record<string,Assignment['status']>>({}),[message,setMessage]=useState('');async function change(a:Assignment,status:Assignment['status']){const previous=statuses[a.id]??a.status;setStatuses(v=>({...v,[a.id]:status}));setMessage('');try{await req(`/assignments/${a.id}/status`,loadAuth()?.token||'',{method:'PATCH',body:JSON.stringify({status})});setMessage(`${a.title}已${status==='open'?'开放':'关闭'}提交`)}catch(e){setStatuses(v=>({...v,[a.id]:previous}));setMessage(e instanceof Error?e.message:'状态更新失败')}}return <section className="panel"><Title title="全部作业" note="管理作业并跟踪班级提交情况"><button className="primary" onClick={()=>go('publish')}>＋ 发布作业</button></Title>{message&&<p className="inline-message">{message}</p>}<div className="atable"><div className="row th"><span>作业</span><span>截止时间</span><span>提交</span><span>平均分</span><span>提交状态</span></div>{as.map(a=>{const sub=ss.filter(s=>s.assignmentId===a.id),avg=sub.length?Math.round(sub.reduce((n,s)=>n+(s.evaluation?.total||0),0)/sub.length):'—',status=statuses[a.id]??a.status;return <div className="row" key={a.id}><span className="aname"><i>{a.language.slice(0,2)}</i><b>{a.title}<small>{a.description||'暂无作业说明'} · 每人最多 {a.maxSubmissions} 次</small></b></span><span>{fmt(a.dueAt)}</span><b>{sub.length}</b><b>{avg}</b><select className={`status-select ${status}`} value={status} onChange={e=>void change(a,e.target.value as Assignment['status'])}><option value="open">开放提交</option><option value="closed">关闭提交</option></select></div>})}</div></section>}
function StudentAssignments({as,ss,go}:{as:Assignment[];ss:Submission[];go:(v:View)=>void}){const[f,setF]=useState('all'),[teacher,setTeacher]=useState('all'),teachers=Array.from(new Map(as.map(a=>[a.teacherId,a.teacherName||'未命名教师'])).entries()),list=as.filter(a=>(teacher==='all'||a.teacherId===teacher)&&(f==='all'||(f==='done')===ss.some(s=>s.assignmentId===a.id)));return <><Title title="课程作业" note="查看要求、截止时间和提交状态"><div className="assignment-controls"><select aria-label="按教师筛选" value={teacher} onChange={e=>setTeacher(e.target.value)}><option value="all">全部教师</option>{teachers.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><div className="tabs">{[['all','全部'],['todo','待提交'],['done','已提交']].map(x=><button className={f===x[0]?'on':''} onClick={()=>setF(x[0])} key={x[0]}>{x[1]}</button>)}</div></div></Title><div className="cards">{list.map(a=>{const sub=ss.find(s=>s.assignmentId===a.id);return <article key={a.id}><header><b>{ico.code} {a.language}</b><i className={`status ${sub?'done':left(a.dueAt)<0?'closed':'open'}`}>{sub?'已提交':left(a.dueAt)<0?'已截止':'待提交'}</i></header><h3>{a.title}</h3><p className="teacher-name">教师：{a.teacherName||'未命名教师'}</p><p>{a.description||'教师暂未添加作业说明。'}</p><div>{a.rubric.slice(0,3).map(r=><small key={r.key}>{r.name} {r.weight}%</small>)}</div><footer><span>◷ {left(a.dueAt)<0?`${-left(a.dueAt)} 天前截止`:`${left(a.dueAt)} 天后截止`}</span>{sub?<Score n={sub.evaluation?.total}/>:<button onClick={()=>go('submissions')}>去提交 ›</button>}</footer></article>})}{!list.length&&<Empty text="没有符合当前筛选条件的作业"/>}</div></>}
function Submissions({teacher,as,ss,pick}:{teacher:boolean;as:Assignment[];ss:Submission[];pick:(s:Submission)=>void}){const[q,setQ]=useState(''),[aid,setAid]=useState('all');const list=useMemo(()=>ss.filter(s=>(aid==='all'||s.assignmentId===aid)&&(!q||(s.studentName+as.find(a=>a.id===s.assignmentId)?.title).toLowerCase().includes(q.toLowerCase()))),[q,aid,ss,as]);return <>{!teacher&&<StudentSubmit assignments={as}/>}<section className="panel"><Title title={teacher?'学生提交列表':'我的提交记录'} note={teacher?'查看每位学生的代码与评估结果':'回顾历史版本与自动评估反馈'}/><div className="filters"><label>{ico.search}<input value={q} onChange={e=>setQ(e.target.value)} placeholder={teacher?'搜索学生或作业':'搜索作业'}/></label><select value={aid} onChange={e=>setAid(e.target.value)}><option value="all">全部作业</option>{as.map(a=><option value={a.id} key={a.id}>{a.title}</option>)}</select></div><div className="stable"><div className="srow th"><span>{teacher?'学生':'作业'}</span><span>{teacher?'作业':'提交时间'}</span><span>状态</span><span>得分</span><span/></div>{list.map(s=><button className="srow" onClick={()=>pick(s)} key={s.id}><span className="student"><i>{(teacher?s.studentName:as.find(a=>a.id===s.assignmentId)?.title||'作')[0]}</i><b>{teacher?s.studentName:as.find(a=>a.id===s.assignmentId)?.title}</b></span><span>{teacher?as.find(a=>a.id===s.assignmentId)?.title:fmt(s.submittedAt)}<small>{teacher&&fmt(s.submittedAt)}</small></span><i className="status done">已评估</i><Score n={s.evaluation?.total}/><b>›</b></button>)}</div>{!list.length&&<Empty text="没有符合条件的提交"/>}</section></>}
function StudentSubmit({assignments}:{assignments:Assignment[]}){
 const token=loadAuth()?.token||'',[history,setHistory]=useState<Submission[]>([]),[id,setId]=useState(assignments[0]?.id||''),[code,setCode]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 const refresh=()=>req<Submission[]>('/submissions',token).then(setHistory)
 useEffect(()=>{void refresh()},[])
 const available=assignments.filter(a=>a.status==='open'&&history.filter(s=>s.assignmentId===a.id).length<a.maxSubmissions)
 useEffect(()=>{if(!available.some(a=>a.id===id))setId(available[0]?.id||'')},[history,assignments])
 const selected=assignments.find(a=>a.id===id),used=history.filter(s=>s.assignmentId===id).length
 async function send(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');try{await req('/submissions',token,{method:'POST',body:JSON.stringify({assignmentId:id,code})});setCode('');setMsg('提交成功，本次评价已加入历史记录。');await refresh()}catch(e){setMsg(e instanceof Error?e.message:'提交失败')}finally{setBusy(false)}}
 return <section className="panel submitbox"><Title title="提交新代码" note="每次提交及其评价都会保留在下方历史记录中"/><form onSubmit={send}><select required value={id} onChange={e=>setId(e.target.value)}><option value="">请选择还有提交次数的作业</option>{available.map(a=><option key={a.id} value={a.id}>{a.title} · {history.filter(s=>s.assignmentId===a.id).length}/{a.maxSubmissions} 次</option>)}</select><textarea required value={code} onChange={e=>setCode(e.target.value)} placeholder="在这里粘贴代码…"/><button className="primary" disabled={busy||!id}>{busy?'评估中…':'提交并评估'}</button></form>{selected&&<small className="attempt-hint">本作业已提交 {used} 次，还可提交 {Math.max(0,selected.maxSubmissions-used)} 次</small>}{!available.length&&<small className="attempt-hint limit">所有作业均已达到提交次数上限</small>}{msg&&<small className="submitmsg">{msg}</small>}</section>}
function Detail({sub,assignment,back}:{sub:Submission;assignment?:Assignment;back:()=>void}){return <><button className="back" onClick={back}>‹ 返回提交列表</button><Title title={assignment?.title||'作业提交'} note={`${sub.studentName} · ${fmt(sub.submittedAt)}`}><Score n={sub.evaluation?.total}/></Title><div className="detail"><section className="panel"><Head name={`提交代码 · ${assignment?.language||''}`}/><pre>{sub.code}</pre></section><section className="panel"><h3 className="ai">✦ AI 评估反馈</h3>{sub.evaluation?<><p>{sub.evaluation.summary}</p>{sub.evaluation.dimensions.map(d=><div className="dimension"><span><b>{d.name}</b><strong>{d.score}/{d.maxScore}</strong></span><i><b style={{width:`${d.score/d.maxScore*100}%`}}/></i><p>{d.evidence}</p><small>建议：{d.suggestion}</small></div>)}</>:<Empty text="评估正在生成"/>}</section></div></>}
function Publish({token,done}:{token:string;done:()=>Promise<void>}){
 const[t,setT]=useState(''),[lang,setLang]=useState('Python'),[desc,setDesc]=useState(''),[due,setDue]=useState(''),[max,setMax]=useState(3),[status,setStatus]=useState<Assignment['status']>('open'),[llm,setLlm]=useState(true),[err,setErr]=useState(''),[rubric,setRubric]=useState<Rubric[]>([{key:'correctness',name:'功能实现',description:'功能符合题目要求',weight:60},{key:'quality',name:'代码质量',description:'结构清晰、命名合理、易于维护',weight:40}])
 const total=rubric.reduce((n,r)=>n+r.weight,0),update=(index:number,patch:Partial<Rubric>)=>setRubric(items=>items.map((r,i)=>i===index?{...r,...patch}:r)),remove=(index:number)=>setRubric(items=>items.filter((_,i)=>i!==index)),add=()=>setRubric(items=>[...items,{key:`criterion_${Date.now()}`,name:'',description:'',weight:0}])
 async function go(e:FormEvent){e.preventDefault();if(total!==100){setErr('评分项权重之和必须为 100%');return}try{await req('/assignments',token,{method:'POST',body:JSON.stringify({title:t,language:lang,description:desc,status,maxSubmissions:max,dueAt:new Date(due).toISOString(),llmEvaluationEnabled:llm,rubric})});await done()}catch(e){setErr(e instanceof Error?e.message:'发布失败')}}
 return <section className="panel publish"><Title title="创建新作业" note="按本次作业目标设置评分项、权重和提交规则"/><form onSubmit={go}><label className="wide">作业标题<input required value={t} onChange={e=>setT(e.target.value)} placeholder="例如：实现 LRU 缓存"/></label><label>编程语言<select value={lang} onChange={e=>setLang(e.target.value)}><option>Python</option><option>Go</option><option>Java</option><option>C++</option></select></label><label>截止时间<input required type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><label>初始提交状态<select value={status} onChange={e=>setStatus(e.target.value as Assignment['status'])}><option value="open">开放提交</option><option value="closed">关闭提交</option></select></label><label>每名学生最多提交次数<input required type="number" min="1" max="100" value={max} onChange={e=>setMax(Number(e.target.value))}/></label><label className="wide">作业说明<textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="描述任务目标、输入输出、约束条件和示例…"/></label><section className="rubric-editor wide"><header><span><b>评分量规</b><small>权重合计必须等于 100%</small></span><strong className={total===100?'valid':'invalid'}>{total}%</strong></header>{rubric.map((r,index)=><div className="rubric-row" key={r.key}><input required value={r.name} onChange={e=>update(index,{name:e.target.value})} placeholder="评分项名称"/><input required value={r.description} onChange={e=>update(index,{description:e.target.value})} placeholder="评判标准说明"/><label><input required type="number" min="1" max="100" value={r.weight} onChange={e=>update(index,{weight:Number(e.target.value)})}/><span>%</span></label><button type="button" disabled={rubric.length===1} onClick={()=>remove(index)}>删除</button></div>)}<button className="add-criterion" type="button" onClick={add}>＋ 添加评分项</button></section><label className="toggle wide"><input type="checkbox" checked={llm} onChange={e=>setLlm(e.target.checked)}/><i/><span><b>启用 AI 深度评估</b><small>根据上方量规生成逐项评分、证据与建议</small></span></label>{err&&<i className="error wide">{err}</i>}<footer className="wide"><button className="primary" disabled={total!==100}>发布作业</button></footer></form></section>}
export default App
